Repository naveen3011/WebD_project_hacktober2023, pull requests merged in 2022-10, with the labels that each got.

#60 add sound-board
  sound-board/index.html
  sound-board/script.js
  sound-board/sounds/applause.mp3
  sound-board/sounds/boo.mp3
  sound-board/sounds/gasp.mp3
  sound-board/sounds/tada.mp3
  sound-board/sounds/victory.mp3
  sound-board/sounds/wrong.mp3
  sound-board/style.css
Labels: hactoberfest-accepted, hactoberfest

#72 Color Game
  Color_game/colorGame.css
  Color_game/colorGame.js
  Color_game/index.html
Labels: hactoberfest-accepted, hactoberfest

#88 add blurry loading
  blurry-loading/index.html
  blurry-loading/script.js
  blurry-loading/style.css
  double-click-heart/index.html
  double-click-heart/script.js
  double-click-heart/style.css
Labels: good first issue, hactoberfest-accepted, hactoberfest

#59 Added simple frontend Javascript project RGB-HEX Converter
  rgb-hex-converter/converter.js
  rgb-hex-converter/index.html
  rgb-hex-converter/style.css
Labels: hactoberfest-accepted, hactoberfest

#46 Created_Travelling website
  Travelling_website
Labels: good first issue, hactoberfest-accepted, hactoberfest

#97 Its anmated webpage
  anime.html
  index.css
Labels: hactoberfest-accepted, hactoberfest

#98 Add files via upload
  onlinePayment/index.html
  onlinePayment/style.css
Labels: hactoberfest-accepted, hactoberfest

#99 Food Website
  Foodento/fries.jpg
  Foodento/index.html
  Foodento/js/script.js
  Foodento/noodles.jpg
  Foodento/pizza.jpg
  Foodento/style1.css
Labels: hactoberfest-accepted, hactoberfest

#105 SimpL eSports Portfolio
  SimpL-ESports Portfolio/app.js
  SimpL-ESports Portfolio/game1/dicee.html
  SimpL-ESports Portfolio/game1/images2/dice1.png
  SimpL-ESports Portfolio/game1/images2/dice2.png
  SimpL-ESports Portfolio/game1/images2/dice3.png
  SimpL-ESports Portfolio/game1/images2/dice4.png
  SimpL-ESports Portfolio/game1/images2/dice5.png
  SimpL-ESports Portfolio/game1/images2/dice6.png
  SimpL-ESports Portfolio/game1/myscript.js
  SimpL-ESports Portfolio/game1/styles3.css
  SimpL-ESports Portfolio/game2/.DS_Store
  SimpL-ESports Portfolio/game2/images/crash.png
  SimpL-ESports Portfolio/game2/images/kick.png
  SimpL-ESports Portfolio/game2/images/snare.png
  SimpL-ESports Portfolio/game2/images/tom1.png
  SimpL-ESports Portfolio/game2/images/tom2.png
  SimpL-ESports Portfolio/game2/images/tom3.png
  SimpL-ESports Portfolio/game2/images/tom4.png
  SimpL-ESports Portfolio/game2/index.html
  SimpL-ESports Portfolio/game2/index.js
  SimpL-ESports Portfolio/game2/sounds/crash.mp3
  SimpL-ESports Portfolio/game2/sounds/kick-bass.mp3
  SimpL-ESports Portfolio/game2/sounds/snare.mp3
  SimpL-ESports Portfolio/game2/sounds/tom-1.mp3
  SimpL-ESports Portfolio/game2/sounds/tom-2.mp3
  SimpL-ESports Portfolio/game2/sounds/tom-3.mp3
  SimpL-ESports Portfolio/game2/sounds/tom-4.mp3
  SimpL-ESports Portfolio/game2/styles.css
  SimpL-ESports Portfolio/img/2dice.png
  SimpL-ESports Portfolio/img/FAVICON.png
  SimpL-ESports Portfolio/img/blog1.jpg
  SimpL-ESports Portfolio/img/blog2.jpg
  SimpL-ESports Portfolio/img/blog3.jpg
  SimpL-ESports Portfolio/img/drumop.png
  SimpL-ESports Portfolio/img/img1.jpg
  SimpL-ESports Portfolio/img/img2.jpg
  SimpL-ESports Portfolio/img/img3.jpg
  SimpL-ESports Portfolio/img/img4.jpg
  SimpL-ESports Portfolio/img/img5.jpg
  SimpL-ESports Portfolio/img/img6.jpg
  SimpL-ESports Portfolio/img/newsimpllogo.jpg
  SimpL-ESports Portfolio/img/piano.png
  SimpL-ESports Portfolio/index.html
  SimpL-ESports Portfolio/styles/styles.css
Labels: hactoberfest-accepted, hactoberfest

#116 Joke teller
  joke teller/favicon.png
  joke teller/index.html
  joke teller/robot.gif
  joke teller/script.js
  joke teller/style.css
  university-site/about.html
  university-site/blog.html
  university-site/contact.html
  university-site/courses.html
  university-site/images/about.jpg
  university-site/images/background.jpg
  university-site/images/banner.png
  university-site/images/banner2.jpg
  university-site/images/basketball.png
  university-site/images/cafeteria.png
  university-site/images/certificate.jpg
  university-site/images/library.png
  university-site/images/logo.png
  university-site/images/london.png
  university-site/images/newyork.png
  university-site/images/user1.jpg
  university-site/images/user2.jpg
  university-site/images/washington.png
  university-site/index.html
  university-site/style.css
Labels: good first issue, hactoberfest-accepted, hactoberfest

#123 Added a furniture store website
  Furniture Website/chair-1.jpg
  Furniture Website/chair-2.jpg
  Furniture Website/chair-3.jpg
  Furniture Website/customers.jpg
  Furniture Website/hero.jpg
  Furniture Website/index.html
  Furniture Website/style.css
Labels: hactoberfest-accepted, hactoberfest

#134 Tourism spots in India website
  Tourism-Spot/index.html
  Tourism-Spot/script.js
  Tourism-Spot/style.css
Labels: hactoberfest-accepted, hactoberfest

#135 Vertical-slider
  double-vertical-slider/index.html
  double-vertical-slider/script.js
  double-vertical-slider/style.css
Labels: hactoberfest-accepted, hactoberfest

#136 Drawing-board
  drawing-app/index.html
  drawing-app/script.js
  drawing-app/style.css
Labels: hactoberfest-accepted, hactoberfest

#137 drag-n-drop project
  drag-n-drop/index.html
  drag-n-drop/script.js
  drag-n-drop/style.css
Labels: hactoberfest-accepted, hactoberfest

#138 Multiply-game
  MultiplicationGame/index.html
  MultiplicationGame/javascript.js
  MultiplicationGame/screenshots/multiplicationscreen1.png
  MultiplicationGame/screenshots/multiplicationscreen2.png
  MultiplicationGame/screenshots/multiplicationscreen3.png
  MultiplicationGame/screenshots/multiplicationscreen4.png
  MultiplicationGame/style.css
Labels: hactoberfest-accepted, hactoberfest

#140 Color_Switch
  color_switch/index.html
  color_switch/script.js
  color_switch/style.css
Labels: hactoberfest-accepted, hactoberfest

#144 Add files via upload
  live-user-filter/index.html
  live-user-filter/script.js
  live-user-filter/style.css
  movie-app/index.html
  movie-app/script.js
  movie-app/style.css
Labels: hactoberfest-accepted, hactoberfest

#145 kinetic-loader
  kinetic-loader/index.html
  kinetic-loader/style.css
Labels: hactoberfest-accepted, hactoberfest

#147 feedback-ui-design
  feedback-ui-design/index.html
  feedback-ui-design/script.js
  feedback-ui-design/style.css
Labels: hactoberfest-accepted, hactoberfest

#150 Added qr code project
  .idea/.gitignore
  .idea/WebD_project_hacktober2022.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  QR code project/css/styles.css
  QR code project/images/favicon-32x32.png
  QR code project/images/qr.png
  QR code project/index.html
Labels: hactoberfest-accepted, hactoberfest

#152 Add files via upload
  BG1.jpeg
  BG2.jpg
  BG3.jpg
  BG4.jpg
  index.html
  jai.html
  mockup1.png
  style.css
Labels: hactoberfest-accepted, hactoberfest

#153 Add files via upload
  TinDog-Start-master/README.md
  TinDog-Start-master/abhi.txt
  TinDog-Start-master/css/styles.css
  TinDog-Start-master/images/TechCrunch.png
  TinDog-Start-master/images/bizinsider.png
  TinDog-Start-master/images/dog-img.jpg
  TinDog-Start-master/images/iphone6.png
  TinDog-Start-master/images/lady-img.jpg
  TinDog-Start-master/images/mashable.png
  TinDog-Start-master/images/tnw.png
  TinDog-Start-master/index.html
  Zomato_clone/index.html
  Zomato_clone/style.css
Labels: hactoberfest-accepted, hactoberfest

#156 Add files via upload
  event-keycodes/dark-style.css
  event-keycodes/index.html
  event-keycodes/script.js
Labels: hactoberfest-accepted, hactoberfest

#155 add product landing page
  Product landing page/cfgtocfl_example.pdf
  Product landing page/high.ong.jpeg
  Product landing page/high.png
  Product landing page/index.html
  Product landing page/logo.png
  Product landing page/round.png
  Product landing page/style.css
  Product landing page/v.png
Labels: hactoberfest-accepted, hactoberfest

#157 password-generator
  password-generator/index.html
  password-generator/script.js
  password-generator/style.css
Labels: hactoberfest-accepted, hactoberfest

#158 pokedex
  pokedex/index.html
  pokedex/script.js
  pokedex/style.css
Labels: hactoberfest-accepted, hactoberfest

#159 Chess Club Site added
  Chess_Club_Website/Readme.md
  Chess_Club_Website/gallery/imgg1.jpg
  Chess_Club_Website/gallery/imgg10.jpg
  Chess_Club_Website/gallery/imgg11.jpg
  Chess_Club_Website/gallery/imgg12.jpg
  Chess_Club_Website/gallery/imgg2.jpg
  Chess_Club_Website/gallery/imgg3.jpg
  Chess_Club_Website/gallery/imgg4.jpg
  Chess_Club_Website/gallery/imgg5.jpg
  Chess_Club_Website/gallery/imgg6.jpg
  Chess_Club_Website/gallery/imgg7.jpg
  Chess_Club_Website/gallery/imgg8.jpg
  Chess_Club_Website/gallery/imgg9.jpg
  Chess_Club_Website/img/1.png
  Chess_Club_Website/img/2.png
  Chess_Club_Website/img/3.png
  Chess_Club_Website/img/4.png
  Chess_Club_Website/img/5.png
  Chess_Club_Website/img/R.jpg
  Chess_Club_Website/img/background1.jpg
  Chess_Club_Website/img/image1.jpg
  Chess_Club_Website/img/image1.png
  Chess_Club_Website/img/image2.jpg
  Chess_Club_Website/img/image2.png
  Chess_Club_Website/img/image3.jpg
  Chess_Club_Website/index.html
  Chess_Club_Website/resp.css
  Chess_Club_Website/style.css
Labels: hactoberfest-accepted, hactoberfest

#161 Added Store Finding and Advertising Web App
  .vscode/settings.json
  Store Exploring Website/README.md
  Store Exploring Website/package-lock.json
  Store Exploring Website/package.json
  Store Exploring Website/public/images/addstore.png
  Store Exploring Website/public/images/baker.png
  Store Exploring Website/public/images/butcher.png
  Store Exploring Website/public/images/chemist.png
  Store Exploring Website/public/images/grocery.png
  Store Exploring Website/public/images/main.png
  Store Exploring Website/public/images/main1.png
  Store Exploring Website/public/images/main2.png
  Store Exploring Website/public/images/main3.png
  Store Exploring Website/public/images/stationery.png
  Store Exploring Website/public/index.html
  Store Exploring Website/src/App.css
  Store Exploring Website/src/App.jsx
  Store Exploring Website/src/Notification.js
  Store Exploring Website/src/app/store.js
  Store Exploring Website/src/components/Body/Add-Update/addstore.css
  Store Exploring Website/src/components/Body/Add-Update/index.jsx
  Store Exploring Website/src/components/Body/AddStore/index.jsx
  Store Exploring Website/src/components/Body/Catalogue/StoreItem/horizontal.jsx
  Store Exploring Website/src/components/Body/Catalogue/StoreItem/storeitem.css
  Store Exploring Website/src/components/Body/Catalogue/catalogue.css
  Store Exploring Website/src/components/Body/Catalogue/index.jsx
  Store Exploring Website/src/components/Body/Home/home.css
  Store Exploring Website/src/components/Body/Home/index.jsx
  Store Exploring Website/src/components/Header/index.jsx
  Store Exploring Website/src/components/Header/nav.css
  Store Exploring Website/src/features/storesSlice.js
  Store Exploring Website/src/index.css
  Store Exploring Website/src/index.js
  Store Exploring Website/src/initialData/data.js
Labels: hactoberfest-accepted, hactoberfest

#163 Encryption and Decryption Website
  Encryption-Decryption-Website/README.md
  Encryption-Decryption-Website/app.js
  Encryption-Decryption-Website/controller/crypt.js
  Encryption-Decryption-Website/crypter/crypter.js
  Encryption-Decryption-Website/errors/custom-error.js
  Encryption-Decryption-Website/middleware/error-handler-middleware.js
  Encryption-Decryption-Website/middleware/not-found.js
  Encryption-Decryption-Website/package-lock.json
  Encryption-Decryption-Website/package.json
  Encryption-Decryption-Website/public/browser.js
  Encryption-Decryption-Website/public/index.html
  Encryption-Decryption-Website/public/robot.ico
  Encryption-Decryption-Website/public/robot.png
  Encryption-Decryption-Website/public/style.css
  Encryption-Decryption-Website/routes/crypt.js
Labels: hactoberfest-accepted, hactoberfest

#164 Added a Budget Manager Chrome Extention
  budgetmanager/New folder/eventPage.js
  budgetmanager/New folder/icon128.png
  budgetmanager/New folder/icon16.png
  budgetmanager/New folder/icon48.png
  budgetmanager/New folder/jquery-3.6.0.min.js
  budgetmanager/New folder/manifest.json
  budgetmanager/New folder/options.html
  budgetmanager/New folder/options.js
  budgetmanager/New folder/popup.html
  budgetmanager/New folder/popup.js
Labels: hactoberfest-accepted
