Repository naveen3011/WebD_project_hacktober2023, pull requests merged in 2023-10, with the labels that each got.

#169 Add testimonial-box-switcher
  testimonial-box-switcher/index.html
  testimonial-box-switcher/script.js
  testimonial-box-switcher/style.css
Labels: hacktoberfest-accepted, hactoberfest

#170 Add sticky-navigation
  sticky-navigation/index.html
  sticky-navigation/script.js
  sticky-navigation/style.css
Labels: help wanted, hacktoberfest-accepted, hactoberfest

#171 Add split-landing-page
  split-landing-page/index.html
  split-landing-page/ps.jpg
  split-landing-page/script.js
  split-landing-page/style.css
  split-landing-page/xbox.jpg
Labels: good first issue, hacktoberfest-accepted, hactoberfest

#176 [Hacktoberfest'23]: Added QR Code Generator Website
  QR Code Generator/README.md
  QR Code Generator/ash.gif
  QR Code Generator/index.html
  QR Code Generator/style.css
Labels: hacktoberfest-accepted, hactoberfest

#179 twitter sentimental analysis
  application.py
  requirements.txt
Labels: hacktoberfest-accepted, hactoberfest

#181 insect-catch-game
  insect-catch-game/index.html
  insect-catch-game/script.js
  insect-catch-game/style.css
Labels: hacktoberfest-accepted, hactoberfest

#182 incrementing-counter
  incrementing-counter/index.html
  incrementing-counter/script.js
  incrementing-counter/style.css
Labels: hacktoberfest-accepted, hactoberfest

#184 Added the jQuery Usage in Web Developement
  jQuery Usage/README.md
  jQuery Usage/index.html
  jQuery Usage/script.js
Labels: hacktoberfest-accepted, hactoberfest

#187 [Hacktoberfest'23] : Added Image Gallery Website
  Image Gallery Website/README.md
  Image Gallery Website/index.html
  Image Gallery Website/script.js
  Image Gallery Website/search-img.jpg
  Image Gallery Website/style.css
Labels: hacktoberfest-accepted, hactoberfest
